version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - "pythondata:/var/lib/postgresql/pythondata"
      - ./book-store/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
      POSTGRES_PORT: 5432
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - 5432:5432
  bookstore:
    image: lekan2910/book-store
    deploy:
      replicas: 2
    ports:
      - 5000:5000
    depends_on:
      - db
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  pythondata:
